# Generated by Django 4.0.6 on 2023-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems_detailssets',
            old_name='detailsset_id',
            new_name='detailsset',
        ),
    ]
