# Generated by Django 4.0.6 on 2023-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_rename_detailsset_id_problems_detailssets_detailsset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems_detailssets',
            name='detailsset',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
