# Generated by Django 4.0.6 on 2023-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_solutions_solutions_datastructures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='detailsset',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='problems_detailssets',
        ),
    ]
